var levels = [
	[
		["Brick", 0, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 1, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 2, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 3, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 4, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 5, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 6, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 7, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 8, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 9, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 10, 0, brickWidth, brickHeight, "red", 1],

		["Brick", 1, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 2, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 3, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 4, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 5, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 6, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 7, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 8, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 9, 1, brickWidth, brickHeight, "cyan", 1],

		["Brick", 2, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 3, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 4, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 5, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 6, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 7, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 8, 2, brickWidth, brickHeight, "red", 1],

		["Brick", 3, 3, brickWidth, brickHeight, "cyan", 1],
		["Brick", 4, 3, brickWidth, brickHeight, "cyan", 1],
		["Brick", 5, 3, brickWidth, brickHeight, "cyan", 1],
		["Brick", 6, 3, brickWidth, brickHeight, "cyan", 1],
		["Brick", 7, 3, brickWidth, brickHeight, "cyan", 1],

		["Brick", 5, 9, brickWidth, brickHeight, "gold", 3]
	],
	[
		["Brick", 4, 0, brickWidth, brickHeight, "green", 1],
		["Brick", 5, 0, brickWidth, brickHeight, "green", 1],
		["Brick", 6, 0, brickWidth, brickHeight, "green", 1],

		["Brick", 3, 1, brickWidth, brickHeight, "orange", 1],
		["Brick", 4, 1, brickWidth, brickHeight, "orange", 1],
		["Brick", 5, 1, brickWidth, brickHeight, "orange", 1],
		["Brick", 6, 1, brickWidth, brickHeight, "orange", 1],
		["Brick", 7, 1, brickWidth, brickHeight, "orange", 1],

		["Brick", 2, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 3, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 4, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 5, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 6, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 7, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 8, 2, brickWidth, brickHeight, "green", 1],

		["Brick", 0, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 1, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 2, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 3, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 4, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 5, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 6, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 7, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 8, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 9, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 10, 3, brickWidth, brickHeight, "orange", 1],

		["Brick", 2, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 3, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 4, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 5, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 6, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 7, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 8, 4, brickWidth, brickHeight, "green", 1],

		["Brick", 3, 5, brickWidth, brickHeight, "orange", 1],
		["Brick", 4, 5, brickWidth, brickHeight, "orange", 1],
		["Brick", 5, 5, brickWidth, brickHeight, "orange", 1],
		["Brick", 6, 5, brickWidth, brickHeight, "orange", 1],
		["Brick", 7, 5, brickWidth, brickHeight, "orange", 1],

		["Brick", 4, 6, brickWidth, brickHeight, "green", 1],
		["Brick", 5, 6, brickWidth, brickHeight, "green", 1],
		["Brick", 6, 6, brickWidth, brickHeight, "green", 1],
	]
]