var levels = [
	[
		["Brick", tile.row(0), tile.col(0), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(1), tile.col(0), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(2), tile.col(0), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(3), tile.col(0), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(4), tile.col(0), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(5), tile.col(0), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(6), tile.col(0), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(7), tile.col(0), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(8), tile.col(0), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(9), tile.col(0), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(10), tile.col(0), brickWidth, brickHeight, "red", 1],

		["Brick", tile.row(1), tile.col(1), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(2), tile.col(1), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(3), tile.col(1), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(4), tile.col(1), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(5), tile.col(1), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(6), tile.col(1), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(7), tile.col(1), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(8), tile.col(1), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(9), tile.col(1), brickWidth, brickHeight, "cyan", 1],

		["Brick", tile.row(2), tile.col(2), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(3), tile.col(2), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(4), tile.col(2), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(5), tile.col(2), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(6), tile.col(2), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(7), tile.col(2), brickWidth, brickHeight, "red", 1],
		["Brick", tile.row(8), tile.col(2), brickWidth, brickHeight, "red", 1],

		["Brick", tile.row(3), tile.col(3), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(4), tile.col(3), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(5), tile.col(3), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(6), tile.col(3), brickWidth, brickHeight, "cyan", 1],
		["Brick", tile.row(7), tile.col(3), brickWidth, brickHeight, "cyan", 1],

		["Brick", tile.row(5), tile.col(9), brickWidth, brickHeight, "gold", 3]
	],
	[
		["Brick", tile.row(4), tile.col(0), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(5), tile.col(0), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(6), tile.col(0), brickWidth, brickHeight, "green", 1],

		["Brick", tile.row(3), tile.col(1), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(4), tile.col(1), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(5), tile.col(1), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(6), tile.col(1), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(7), tile.col(1), brickWidth, brickHeight, "orange", 1],

		["Brick", tile.row(2), tile.col(2), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(3), tile.col(2), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(4), tile.col(2), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(5), tile.col(2), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(6), tile.col(2), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(7), tile.col(2), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(8), tile.col(2), brickWidth, brickHeight, "green", 1],

		["Brick", tile.row(0), tile.col(3), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(1), tile.col(3), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(2), tile.col(3), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(3), tile.col(3), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(4), tile.col(3), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(5), tile.col(3), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(6), tile.col(3), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(7), tile.col(3), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(8), tile.col(3), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(9), tile.col(3), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(10), tile.col(3), brickWidth, brickHeight, "orange", 1],

		["Brick", tile.row(2), tile.col(4), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(3), tile.col(4), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(4), tile.col(4), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(5), tile.col(4), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(6), tile.col(4), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(7), tile.col(4), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(8), tile.col(4), brickWidth, brickHeight, "green", 1],

		["Brick", tile.row(3), tile.col(5), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(4), tile.col(5), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(5), tile.col(5), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(6), tile.col(5), brickWidth, brickHeight, "orange", 1],
		["Brick", tile.row(7), tile.col(5), brickWidth, brickHeight, "orange", 1],

		["Brick", tile.row(4), tile.col(6), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(5), tile.col(6), brickWidth, brickHeight, "green", 1],
		["Brick", tile.row(6), tile.col(6), brickWidth, brickHeight, "green", 1],
	]
]