var levels = [
	[
		["Brick", 1, 1, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 9, 1, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 0, 2, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 1, 2, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 9, 2, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 10, 2, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 3, 3, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 4, 3, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 5, 3, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 6, 3, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 7, 3, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 2, 4, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 3, 4, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 4, 4, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 5, 4, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 6, 4, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 7, 4, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 8, 4, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 2, 5, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Block", 3, 5, brickWidth, brickHeight, "red"],
		["Block", 4, 5, brickWidth, brickHeight, "red"],
		["Brick", 5, 5, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Block", 6, 5, brickWidth, brickHeight, "red"],
		["Block", 7, 5, brickWidth, brickHeight, "red"],
		["Brick", 8, 5, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 2, 6, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 3, 6, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 4, 6, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 5, 6, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 6, 6, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 7, 6, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 8, 6, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 3, 7, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 4, 7, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 5, 7, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 6, 7, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 7, 7, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 0, 8, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 1, 8, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 3, 8, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 5, 8, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 7, 8, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 9, 8, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 10, 8, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 1, 9, brickWidth, brickHeight, "WhiteSmoke", 1],
		["Brick", 9, 9, brickWidth, brickHeight, "WhiteSmoke", 1],
	],
	[
		["Block", 0, 0, brickWidth, brickHeight, "red"],
		["Brick", 1, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 2, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 3, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 4, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 5, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 6, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 7, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 8, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 9, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 10, 0, brickWidth, brickHeight, "red", 1],
		["Brick", 1, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 2, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 3, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 4, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 5, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 6, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 7, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 8, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 9, 1, brickWidth, brickHeight, "cyan", 1],
		["Brick", 2, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 3, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 4, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 5, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 6, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 7, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 8, 2, brickWidth, brickHeight, "red", 1],
		["Brick", 3, 3, brickWidth, brickHeight, "cyan", 1],
		["Brick", 4, 3, brickWidth, brickHeight, "cyan", 1],
		["Brick", 5, 3, brickWidth, brickHeight, "cyan", 1],
		["Brick", 6, 3, brickWidth, brickHeight, "cyan", 1],
		["Brick", 7, 3, brickWidth, brickHeight, "cyan", 1],
		["Brick", 5, 9, brickWidth, brickHeight, "gold", 3],
	],
	[
		["Brick", 4, 0, brickWidth, brickHeight, "green", 1],
		["Brick", 5, 0, brickWidth, brickHeight, "green", 1],
		["Brick", 6, 0, brickWidth, brickHeight, "green", 1],
		["Brick", 3, 1, brickWidth, brickHeight, "orange", 1],
		["Brick", 4, 1, brickWidth, brickHeight, "orange", 1],
		["Brick", 5, 1, brickWidth, brickHeight, "orange", 1],
		["Brick", 6, 1, brickWidth, brickHeight, "orange", 1],
		["Brick", 7, 1, brickWidth, brickHeight, "orange", 1],
		["Brick", 2, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 3, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 4, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 5, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 6, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 7, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 8, 2, brickWidth, brickHeight, "green", 1],
		["Brick", 0, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 1, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 2, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 3, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 4, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 5, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 6, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 7, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 8, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 9, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 10, 3, brickWidth, brickHeight, "orange", 1],
		["Brick", 2, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 3, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 4, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 5, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 6, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 7, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 8, 4, brickWidth, brickHeight, "green", 1],
		["Brick", 3, 5, brickWidth, brickHeight, "orange", 1],
		["Brick", 4, 5, brickWidth, brickHeight, "orange", 1],
		["Brick", 5, 5, brickWidth, brickHeight, "orange", 1],
		["Brick", 6, 5, brickWidth, brickHeight, "orange", 1],
		["Brick", 7, 5, brickWidth, brickHeight, "orange", 1],
		["Brick", 4, 6, brickWidth, brickHeight, "green", 1],
		["Brick", 5, 6, brickWidth, brickHeight, "green", 1],
		["Brick", 6, 6, brickWidth, brickHeight, "green", 1],
	],
]
